##############################################
### 🧑 USUARIOS
##############################################

### 📋 Registro de usuario
POST http://127.0.0.1:5000/registro
Content-Type: application/json

{
  "paterno": "Rodriguez",
  "materno": "Herrera",
  "nombre": "Mafer",
  "edad":25,
  "fecha_nacimiento": "2000-2-17",
  "sexo": "F",
  "direccion": "Av. Central #123",
  "celular": "5551234568",
  "email": "fer@test.com",
  "password": "fer12345",
  "rol":"psicologo"
}

### 🔐 Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "email": "carlos@test.com",
  "password": "Test12345"
}

### 🚪 Logout
GET http://127.0.0.1:5000/logout


##############################################
### 📅 CITAS
##############################################

### 📆 Crear cita
POST http://127.0.0.1:5000/api/citas
Content-Type: application/json

{
  "fecha": "2025-11-10",
  "horainicio": "11:00",
  "horafin": "12:00",
  "descripcioncancelado": null
}

### 📋 Listar citas del usuario autenticado
GET http://127.0.0.1:5000/api/citas

### ❌ Cancelar cita
PUT http://127.0.0.1:5000/api/citas/1/cancelar
Content-Type: application/json

{
  "motivo": "Tuve un imprevisto"
}
